---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 89.169.151.20
      ansible_connection: ssh
      ansible_user: ubuntu
#      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_ssh_private_key_file: /etc/ssh/id_ed25519
#      ansible_connection: docker
#      ansible_become_method: su

vector:
  hosts:
    vector-01:
      ansible_host: 89.169.153.212
      ansible_connection: ssh
      ansible_user: ubuntu
#      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_ssh_private_key_file: /etc/ssh/id_ed25519
#      ansible_connection: docker
#      ansible_become_method: su

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 89.169.152.145
      ansible_connection: ssh
      ansible_user: ubuntu
#      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_ssh_private_key_file: /etc/ssh/id_ed25519